// <auto-generated />
namespace Lesson2HomeTask.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DataMigrationLesson2TaskHome : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DataMigrationLesson2TaskHome));
        
        string IMigrationMetadata.Id
        {
            get { return "201611111039186_DataMigrationLesson2TaskHome"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
